spring.application.name=Diary
spring.config.import=optional:classpath:application-local.properties
server.forward-headers-strategy=framework
server.servlet.session.cookie.same-site=lax
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
